version: "3"
services:
  djarf:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    image: ${ECR_URI}/djarf:latest
  server:
    build: ./nginx
    image: ${ECR_URI}/djarf-server:latest
    ports: ["80:80"]
    depends_on: [djarf]
    links: [djarf]
