# Generated by Django 4.1.7 on 2023-03-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_product_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order2product",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="order2product",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order2products",
                to="commerce.product",
            ),
        ),
        migrations.AddIndex(
            model_name="order2product",
            index=models.Index(
                fields=["order", "product"], name="commerce_or_order_i_156430_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order2product",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_order_product"
            ),
        ),
    ]
