# Generated by Django 4.1.7 on 2023-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_alter_cart_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                null=True, related_name="products", to="commerce.tag"
            ),
        ),
    ]
