# Generated by Django 4.1.7 on 2023-03-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_remove_product_tag_product_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="commerce.tag"
            ),
        ),
    ]
