# Generated by Django 4.1.7 on 2023-03-29 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "commerce",
            "0007_product_description_product_dislikes_product_likes_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        choices=[
                            (0.5, 0.5),
                            (1.0, 1.0),
                            (1.5, 1.5),
                            (2.0, 2.0),
                            (2.5, 2.5),
                            (3.0, 3.0),
                            (3.5, 3.5),
                            (4.0, 4.0),
                            (4.5, 4.5),
                            (5.0, 5.0),
                        ],
                        db_index=True,
                        decimal_places=1,
                        max_digits=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("likes", models.PositiveSmallIntegerField(db_index=True, default=0)),
                (
                    "dislikes",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="commerce.product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "product"), name="unique_reviewer_product"
            ),
        ),
    ]
