# Generated by Django 4.1.7 on 2023-03-29 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commerce", "0010_alter_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_customer_product",
        ),
        migrations.RemoveConstraint(
            model_name="order2product",
            name="unique_order_product",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_reviewer_product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
        migrations.AddField(
            model_name="product",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"), name="cart_unique_customer_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="order2product",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="order2project_unique_order_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "product"), name="review_unique_reviewer_product"
            ),
        ),
        migrations.AddField(
            model_name="reviewlike",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewlike",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_likes",
                to="commerce.review",
            ),
        ),
        migrations.AddField(
            model_name="productlike",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productlike",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_likes",
                to="commerce.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewlike",
            constraint=models.UniqueConstraint(
                fields=("customer", "review"), name="review_like_unique_customer_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="productlike",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"),
                name="product_like_unique_customer_product",
            ),
        ),
    ]
