# Generated by Django 4.1.7 on 2023-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0011_productlike_reviewlike_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order2product",
            name="order2project_unique_order_product",
        ),
        migrations.RemoveConstraint(
            model_name="productlike",
            name="product_like_unique_customer_product",
        ),
        migrations.RemoveConstraint(
            model_name="reviewlike",
            name="review_like_unique_customer_review",
        ),
        migrations.RenameField(
            model_name="productlike",
            old_name="customer",
            new_name="liker",
        ),
        migrations.RenameField(
            model_name="reviewlike",
            old_name="customer",
            new_name="liker",
        ),
        migrations.AddConstraint(
            model_name="order2product",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="order2product_unique_order_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="productlike",
            constraint=models.UniqueConstraint(
                fields=("liker", "product"), name="product_like_unique_liker_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewlike",
            constraint=models.UniqueConstraint(
                fields=("liker", "review"), name="review_like_unique_liker_review"
            ),
        ),
    ]
