# Generated by Django 4.1.7 on 2023-03-30 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0011_remove_cart_unique_customer_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order2product",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="modified",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="modified",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="cart",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="category",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="order2product",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order2product",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
