# Generated by Django 4.1.7 on 2023-03-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0012_remove_order2product_order2project_unique_order_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productlike",
            options={"ordering": ["liker"]},
        ),
        migrations.AlterModelOptions(
            name="reviewlike",
            options={"ordering": ["liker"]},
        ),
    ]
