# Generated by Django 4.1.7 on 2023-04-10 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0012_alter_order2product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="product",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
    ]
