# Generated by Django 4.1.7 on 2023-02-19 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="text",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(verbose_name="date created"),
        ),
    ]
